// Faq.test.js
import React from "react";
import { render, screen } from "@testing-library/react";
// import "@testing-library/jest-dom/extend-expect";
import Faq from "../Faq";

describe("Faq Component", () => {
  test("renders Faq component", () => {
    render(<Faq />);

    // Check if the main heading is rendered
    expect(screen.getByRole("heading", { name: /FAQ/i })).toBeInTheDocument();

    // Check if the subheading is rendered
    expect(screen.getByText(/Frequently Asked Questions/i)).toBeInTheDocument();

    // Check if all FAQ questions are rendered
    const questions = [
      "What is a URL shortener?",
      "How do i use your URL shortener?",
      "Is it free to use?",
      "Is there a limit to the number of links i can shorten?",
      "How long are the short links generated by your platform?",
    ];

    questions.forEach((question) => {
      expect(screen.getByText(question)).toBeInTheDocument();
    });

    // Check if all FAQ answers are rendered
    const answers = [
      "A URL shortener is a service that takes a long URL and converts it into a shorter, more manageable one.",
      "You enter a long URL, and the application generates a shorter version of it. You can use this short URL to redirect to the original long URL.",
      "Yes, our URL shortening service is completely free to use.",
      "No, there are no limit to the number of URL you want to shorten",
      "The length of the short links generated by our platform typically consists of a fixed base URL and a unique identifier. The unique identifier is usually a string of characters (e.g., 7-10 characters) that ensures the short link remains unique. The exact length can vary depending on the implementation, but it is designed to be significantly shorter than the original URL.",
    ];

    answers.forEach((answer) => {
      expect(screen.getByText(answer)).toBeInTheDocument();
    });
  });
});
